# Generated by Django 5.2.8 on 2025-11-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
