# Generated by Django 5.2.8 on 2026-01-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
